# 從 data/Phn.tbl（淡江「無字天書」BKey 的國語點字 → 大千鍵序表，North American
# ASCII 點字編碼）產生 src/syllables.inc。每筆三行：點字方序列、要送的大千鍵、
# 這個音節有效的聲調清單。程式只用前兩行；第三行留作日後校驗。
import os

here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, '..', 'data', 'Phn.tbl')
dst = os.path.join(here, '..', 'src', 'syllables.inc')

lines = open(src, 'rb').read().decode('ascii').replace('\r\n', '\n').split('\n')
tri = [lines[i:i + 3] for i in range(0, len(lines) - 2, 3)]
entries = []
for cells, keys, tones in tri:
    cells, keys, tones = cells.strip(), keys.strip(), tones.strip()
    if not cells or not keys:
        continue
    entries.append((cells, keys, tones))
# 音節 Phn.tbl 沒有、教育部國語辭典（moedict chars.json）卻有字的：
# tools/gen_bopomofo_rules.py 拿 BrlIMEHelper 的規則表對照字典找出來的（見
# docs/braille-table-comparison-2026-09-09.md 第二節）。方序列與 Phn.tbl 同一種
# ASCII 點字寫法；聲調欄寫字典裡出現的聲調。
EXTRA = [
    ('c<', 'xi', '5'),      # ㄌㄛ 咯（輕聲）
    ('du', '2p', '4'),      # ㄉㄣ 扽、㩐
    ('p)', 'qu8', '1'),     # ㄆㄧㄚ 㕷
    ('n=', 'sjp', '2'),     # ㄋㄨㄣ 黁
]
have = {c for c, _, _ in entries}
for cells, keys, tones in EXTRA:
    if cells not in have:
        entries.append((cells, keys, tones + ' (moedict)'))
entries.sort()


# BKey writes the four cells 2-4-6, 1-2-5-6, 1-2-4-5-6 and 4-5 with the
# lower-case variants { | } ~ ; the engine's cell table produces the canonical
# [ \ ] ^ for the same cells. Normalise so a lookup always matches.
CANON = {'{': '[', '|': '\\', '}': ']', '~': '^'}


def canon(s):
    return ''.join(CANON.get(ch, ch) for ch in s)


def c_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


with open(dst, 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by tools/gen_syllables.py from data/Phn.tbl - do not edit by hand.\n')
    f.write('// { braille cells (North American ASCII braille), keys to send on the 大千 layout }\n')
    for cells, keys, tones in entries:
        f.write('{ "%s", "%s" },  // tones %s\n' % (c_escape(canon(cells)), c_escape(keys), tones))
print('entries:', len(entries))
