# 從 JAWS 自己的點字表產生引擎用的兩個 .inc（建置時跑，不是執行時）：
#
#   src/us_unicode.inc  英文單方表的內建備份：US_Unicode.jbt 的 [input]／[ANSI]／
#                       [Unicode ...] 各節，八點電腦點字（點 7 = 大寫）。執行時程式
#                       先找 JAWS 安裝夾裡的同一個檔案；找不到才用這份。
#                       節的優先順序跟執行時的解析器一樣：[input] > [ANSI] > 其餘節
#                       依檔案順序先到先贏；只收單方的項目；[Braille Unicode]
#                       那 256 個點字圖形字元不收（沒定義的方要響鈴，不要默默
#                       打出 ⠿）；控制字元（< 32、127）不收。
#
#   src/nemeth.inc      Nemeth 數學符號的多方序列：來自 JAWS 附的 Liblouis
#                       nemeth.ctb／nemethdefs.cti／en-chardefs.cti（含
#                       loweredDigits6Dots.uti 的數字）。只收 NAMES 裡有中文唸法
#                       的符號；虛擬點（a–f）去掉，含空方（0）的序列不收。
#
# 用法：python gen_tables.py [JAWS 安裝夾]
import os
import re
import sys
import unicodedata

here = os.path.dirname(os.path.abspath(__file__))
src_dir = os.path.join(here, '..', 'src')
jaws = sys.argv[1] if len(sys.argv) > 1 else r'C:\Program Files\Freedom Scientific\JAWS\2026'
liblouis = None
lb = os.path.join(jaws, 'Liblouis')
if os.path.isdir(lb):
    vers = sorted(d for d in os.listdir(lb) if os.path.isdir(os.path.join(lb, d, 'tables')))
    if vers:
        liblouis = os.path.join(lb, vers[-1], 'tables')
if not liblouis:
    sys.exit('找不到 Liblouis tables 夾：' + lb)


def dots_mask(s):
    m = 0
    for ch in s:
        if '1' <= ch <= '8':
            m |= 1 << (int(ch) - 1)
        else:
            return None
    return m


# ---------------------------------------------------------------- US_Unicode.jbt
def parse_jbt(path):
    """回傳 {mask: codepoint}，優先順序同引擎的 LoadJbt。"""
    table = {}
    prio = {}   # mask -> priority number (lower wins)
    sec = ''
    for raw in open(path, encoding='latin-1'):
        line = raw.strip()
        if not line or line.startswith(';'):
            continue
        if line.startswith('[') and line.endswith(']'):     # `[=2467` is the [ character, not a section
            sec = line.lower()
            continue
        if line.startswith('='):                             # `==123456`: the = character
            key, eq, val = '=', '=', line[2:]
        else:
            key, eq, val = line.partition('=')
        if not eq:
            continue
        key = key.strip()
        val = val.strip()
        if not val or ' ' in val:
            continue                       # empty or multi-cell
        if sec == '[table attributes]' or sec == '[braille unicode]':
            continue
        if key == '\\':
            cp = 92                        # the backslash itself (`\=12567`)
        elif key.startswith('\\'):
            try:
                cp = int(key[1:])
            except ValueError:
                continue
        elif key[:2].lower() == 'u+':
            cp = int(key[2:], 16)
        elif len(key) == 1:
            cp = ord(key)
        else:
            continue
        if cp < 32 or cp == 127 or 0x2800 <= cp <= 0x28FF:
            continue
        mask = dots_mask(val)
        if not mask:
            continue
        p = 0 if sec == '[input]' else 1 if sec == '[ansi]' else 2
        if mask in table and prio[mask] <= p:
            continue
        table[mask] = cp
        prio[mask] = p
    return table


jbt = os.path.join(jaws, 'US_Unicode.jbt')
us = parse_jbt(jbt)
# Paul 2026-09-09 校正：US_Unicode.jbt 把 1256 給 |、12567 給 \，台灣點字使用者
# 照北美 ASCII 點字（NABCC）習慣 1256 是反斜線 \。對調這兩方；其他照 JAWS 表。
US_OVERRIDES = {dots_mask('1256'): ord('\\'), dots_mask('12567'): ord('|')}
us.update(US_OVERRIDES)
with open(os.path.join(src_dir, 'us_unicode.inc'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by tools/gen_tables.py from %s - do not edit by hand.\n' % jbt)
    f.write('// { dots (bit 0 = dot 1 ... bit 7 = dot 8), code point }  8-dot US computer braille\n')
    for mask in sorted(us):
        cp = us[mask]
        dots = ''.join(str(i + 1) for i in range(8) if mask & (1 << i))
        # (a backslash at the end of a comment would splice the next line away)
        f.write('{ 0x%02X, 0x%04X },  // %s %s\n' % (mask, cp, dots, 'backslash' if cp == 92 else chr(cp) if cp > 32 else ''))
print('us_unicode.inc:', len(us), 'entries')



# ---------------------------------------------------------------- Nemeth
# 中文唸法：字元 -> 唸法；值可以是 (輸出文字, 唸法)，當打進文字裡的字要跟表裡
# 的字元不同時（減號、撇號、比號用 ASCII，複製到計算機或程式碼裡才有用）。
# JAWS 附的 Liblouis Nemeth 表定義的每個字元都要在這裡有唸法（Paul 2026-09-09：
# 「Nemeth 點字符號尤其數學也要新增，數學是六點輸入的主戰場」）；沒有唸法的
# 字元會列在產生器的輸出裡，不會默默漏掉。台灣數學用語。
NAMES = {
    '0': '0', '1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9',
    # 四則、運算子
    '+': '加', '-': '減', '−': ('-', '減'), '×': '乘', '✕': '乘', '÷': '除', '±': '正負', '∓': '負正',
    '·': '乘點', '⋅': '乘點', '˙': '上點', '¨': '雙點號', '*': '星號', '∗': ('*', '星號'), '/': '斜線', '∕': '除線', '⁄': '分數斜線',
    '∖': '差集', '∘': '小圓', '∣': ('|', '整除'), '∤': '不整除',
    '⊕': '圈加', '⊖': '圈減', '⊗': '圈乘', '⊘': '圈除', '⊙': '圈點', '⊛': '圈星號', '⊜': '圈等於', '⊝': '圈短線',
    '⊞': '方框加', '⊟': '方框減', '⊠': '方框乘', '⊡': '方框點',
    # 關係
    '=': '等於', '≠': '不等於', '<': '小於', '>': '大於', '≤': '小於等於', '≥': '大於等於',
    '≦': '小於等於 雙橫線', '≧': '大於等於 雙橫線', '≨': '小於但不等於', '≩': '大於但不等於',
    '≪': '遠小於', '≫': '遠大於', '⋘': '極小於', '⋙': '極大於', '⋜': '等於或小於', '⋝': '等於或大於',
    '≮': '不小於', '≯': '不大於', '≰': '不小於等於', '≱': '不大於等於',
    '≲': '小於或相似', '≳': '大於或相似', '≴': '不小於或相似', '≵': '不大於或相似',
    '≶': '小於或大於', '≷': '大於或小於', '≸': '不小於或大於', '≹': '不大於或小於',
    '≈': '近似等於', '≅': '全等', '∼': '相似', '~': ('~', '相似'), '≍': '等價', '≭': '不等價',
    '≡': '恆等於', '≢': '不恆等於', '∝': '正比', '∶': (':', '比'), '∷': '比例',
    # 集合
    '∈': '屬於', '∉': '不屬於', '∋': '包含元素', '∌': '不包含元素', '∍': '包含元素',
    '⊂': '子集合', '⊃': '超集合', '⊆': '子集合或等於', '⊇': '超集合或等於',
    '⊄': '非子集合', '⊅': '非超集合', '⊈': '非子集合或等於', '⊉': '非超集合或等於',
    '⊊': '真子集合', '⊋': '真超集合',
    '∪': '聯集', '∩': '交集', '∅': '空集合', '∞': '無限大',
    'ℂ': '複數集', 'ℕ': '自然數集', 'ℝ': '實數集', 'ℤ': '整數集', 'ⅇ': '雙線體 e', 'ℓ': '手寫體 l',
    # 邏輯
    '∴': '所以', '∵': '因為', '∎': '證畢',
    '∀': '對所有', '∃': '存在', '∄': '不存在', '¬': '非', '∧': '且', '∨': '或',
    # 微積分
    '∑': '總和', '∏': '連乘', '∫': '積分', '∬': '雙重積分', '∭': '三重積分',
    '∮': '環積分', '∲': '順時針環積分', '∳': '逆時針環積分',
    '∂': '偏微分', '∇': '梯度',
    # 幾何
    '∥': '平行', '∦': '不平行', '⊥': '垂直',
    '∠': '角', '∡': '有向角', '∢': '球面角', '∟': '直角', '⌢': '弧', '⌣': '凹弧',
    '△': '三角形', '▵': '三角形', '▲': '實心三角形', '▽': '倒三角形', '▼': '實心倒三角形',
    '○': '圓', '◯': '圓', '●': '實心圓', '□': '正方形', '■': '實心正方形', '⋾': '實心正方形',
    '▭': '長方形', '▬': '實心長方形', '▱': '平行四邊形', '▰': '實心平行四邊形', '⏢': '梯形',
    '°': '度', 'Å': ('Å', '埃'),   # U+212B angstrom sign is typed as the ordinary Å U+00C5
    # 其他記號
    '%': '百分號', '‰': '千分號', '‱': '萬分號', '!': '階乘', '′': ("'", '撇號'), '″': ("''", '雙撇號'),
    '…': '刪節號', '¯': '橫線', '―': ('¯', '橫線'), '‾': ('¯', '橫線'),
    '℔': '磅', '†': '劍號', '‡': '雙劍號', '•': '項目符號', '§': '章節號',
    # 貨幣
    '$': '錢號', '¢': '分', '£': '英鎊', '¤': '貨幣符號', '¥': '日圓', '€': '歐元', '₣': '法郎', '₦': '奈拉',
    # 括號
    '(': '左小括號', ')': '右小括號', '[': '左中括號', ']': '右中括號', '{': '左大括號', '}': '右大括號',
    '|': '絕對值', '‖': '範數', '⫴': '三直線', '¦': '斷直線',
    '⟨': '左角括號', '⟩': '右角括號', '⟦': '左白中括號', '⟧': '右白中括號', '⦃': '左白大括號', '⦄': '右白大括號',
    '⌈': '左上取整', '⌉': '右上取整', '⌊': '左下取整', '⌋': '右下取整', '⏞': '上大括號', '⏟': '下大括號',
    # 標點與 ASCII 符號
    ',': '逗號', '.': '點', ';': '分號', ':': '冒號', '?': '問號', '#': '井字號', '@': '小老鼠', '&': '和',
    '\\': '反斜線', '^': '插入號', '_': '底線', '¡': '倒驚嘆號', '¿': '倒問號',
    # 箭頭
    '→': '右箭頭', '←': '左箭頭', '↑': '上箭頭', '↓': '下箭頭', '↔': '左右箭頭', '↕': '上下箭頭',
    '↖': '左上箭頭', '↗': '右上箭頭', '↘': '右下箭頭', '↙': '左下箭頭',
    '⇒': '若則', '⇐': '左雙箭頭', '⇔': '若且唯若', '⇑': '上雙箭頭', '⇓': '下雙箭頭', '⇕': '上下雙箭頭',
    '⇖': '左上雙箭頭', '⇗': '右上雙箭頭', '⇘': '右下雙箭頭', '⇙': '左下雙箭頭',
    '⇚': '左三箭頭', '⇛': '右三箭頭', '↦': '映射到',
    '↚': '左箭頭加斜線', '↛': '右箭頭加斜線', '↮': '左右箭頭加斜線',
    '⇍': '左雙箭頭加斜線', '⇎': '左右雙箭頭加斜線', '⇏': '右雙箭頭加斜線',
    '↜': '左波浪箭頭', '↝': '右波浪箭頭', '↭': '左右波浪箭頭', '⇜': '左扭曲箭頭', '⇝': '右扭曲箭頭',
    '↞': '左雙頭箭頭', '↟': '上雙頭箭頭', '↠': '右雙頭箭頭', '↡': '下雙頭箭頭',
    '↢': '左帶尾箭頭', '↣': '右帶尾箭頭',
    '↤': '左箭頭起自直線', '↥': '上箭頭起自直線', '↧': '下箭頭起自直線', '↨': '上下箭頭帶底線',
    '↩': '左鉤箭頭', '↪': '右鉤箭頭', '↫': '左環箭頭', '↬': '右環箭頭', '↯': '下閃電箭頭',
    '↴': '右轉下箭頭', '↵': '下轉左箭頭', '↺': '逆時針圓箭頭', '↻': '順時針圓箭頭',
    '↼': '左魚叉上鉤', '↽': '左魚叉下鉤', '↾': '上魚叉右鉤', '↿': '上魚叉左鉤',
    '⇀': '右魚叉上鉤', '⇁': '右魚叉下鉤', '⇂': '下魚叉右鉤', '⇃': '下魚叉左鉤',
    '⇄': '右箭頭上左箭頭下', '⇅': '上箭頭左下箭頭右', '⇆': '左箭頭上右箭頭下', '⇵': '下箭頭左上箭頭右',
    '⇇': '左成對箭頭', '⇈': '上成對箭頭', '⇉': '右成對箭頭', '⇊': '下成對箭頭',
    '⇋': '左魚叉上右魚叉下', '⇌': '右魚叉上左魚叉下',
    '⇞': '上箭頭加雙斜線', '⇟': '下箭頭加雙斜線', '⇣': '下虛線箭頭',
    '⇤': '左箭頭至直線', '⇥': '右箭頭至直線',
    '⇦': '左空心箭頭', '⇧': '上空心箭頭', '⇨': '右空心箭頭', '⇩': '下空心箭頭', '⇳': '上下空心箭頭',
    '⇴': '右箭頭帶小圓', '⇶': '右三連箭頭',
    '⇷': '左箭頭加直線', '⇸': '右箭頭加直線', '⇹': '左右箭頭加直線',
    '⇺': '左箭頭加雙直線', '⇻': '右箭頭加雙直線', '⇼': '左右箭頭加雙直線',
    '⇽': '左空頭箭頭', '⇾': '右空頭箭頭', '⇿': '左右空頭箭頭',
}
GREEK = {
    'α': '阿爾法', 'β': '貝塔', 'γ': '伽瑪', 'δ': '德爾塔', 'ε': '艾普西隆', 'ζ': '澤塔',
    'η': '伊塔', 'θ': '西塔', 'ι': '約塔', 'κ': '卡帕', 'λ': '拉姆達', 'μ': '謬',
    'ν': '紐', 'ξ': '克西', 'ο': '歐米克戎', 'π': '派', 'ρ': '羅', 'ς': '尾西格瑪',
    'σ': '西格瑪', 'τ': '陶', 'υ': '宇普西隆', 'φ': '斐', 'χ': '卡伊', 'ψ': '普賽',
    'ω': '歐米伽',
}
for ch, name in GREEK.items():
    NAMES[ch] = name
    up = ch.upper()
    if up != ch:
        NAMES[up] = '大寫 ' + name
# 變體希臘字母（46-4-字母）
for ch, name in {'ϑ': '西塔', 'ϕ': '斐', 'ϖ': '派', 'ϰ': '卡帕', 'ϱ': '羅', 'ϵ': '艾普西隆'}.items():
    NAMES[ch] = '變體 ' + name
NAMES['µ'] = '謬'          # micro sign, same cells as μ

# 不收的字元：它們的方在 Nemeth 裡另有意思，收了會把常用的打法吃掉。
#   " '  引號在 Nemeth 是 236／356（＝數字 8／0）和 356-3（0 加撇號）、6-236（逗號加 8）
#   `    en-chardefs 的重音符是點 4，點 4 是幾十個符號的前置方（Plain 表照樣打得出 `）
#   – —  en-chardefs 的 36-36：兩個減號要照打成 --
#   ¼ ½ ¾ 就是分數指標打出來的 1/4 序列，收了會讓分數開始等五方才唸
#   © ® ™ en-chardefs 用 45-14／45-1235／45-2345，就是「上標 c」；nemethdefs 的 © 是 (C)
#   ° 56-145-1245（en-chardefs）就是「下標 dg」；度用 45-46-16
#   ⋯ ⋮ ⋰ ⋱ 去掉空方後是 25-25-25（333）、146／45／56 加 333（下方／上標／下標 333）
#   U+0093–0096、軟連字號、不斷行連字號：Windows-1252 的控制字元與版面用字
EXCLUDE = set('"\'`') | {'–', '—', '¼', '½', '¾', '©', '®', '™',
                         '⋯', '⋮', '⋰', '⋱', '­', '‑'} | {chr(c) for c in range(0x93, 0x97)} | {''}   # F577 = the contracted → again
EXCLUDE_CELLS = {'56-145-1245'}

# Nemeth 的指標（indicator）：印刷上沒有對應字元，這裡給打進文字裡最接近的寫法。
# Liblouis 用私用區碼 \xf5xx／\xf32x 代表它們（nemeth.ctb 的 math 定義），點位即
# Nemeth 規範。引擎依「分數／根號有沒有開著」決定 3456 是數字符還是分數關、12456
# 是結束符還是大括號；126 之後的 345 打 ](，把根指數收進中括號（√[3](8)）。
# 純指標打不出字也要唸，打字的人才聽得到自己按了什麼。
# 另兩個是 Nemeth 在 UEB 裡的開關符（BANA 2016 規範）：開 456-146、關 456-156；
# nemeth.ctb 只列了關（endcomp 456-156），開的點位是規範原文。
# 字型指標照 BANA：斜體英文字母 46-56、粗體英文字母 456-56（Liblouis 的 begemph
# 46／456 單方就是希臘字母符／標點符號指標，分不開）；結束符照 nemeth.ctb 的
# endemph 46-46／456-456。
INDICATORS = [
    ('456-146', '', 'Nemeth 開始'),
    ('456-156', '', 'Nemeth 結束'),
    ('1456', '(', '分數開始'),          # \xf500
    ('3456', ')', '分數結束'),          # \xf503 (also the numeric indicator)
    ('6-1456', '(', '複分數開始'),      # \xf508
    ('6-34', '/', '複分數線'),          # \xf509
    ('6-456-34', '/', '複分數斜線'),    # \xf50a
    ('6-3456', ')', '複分數結束'),      # \xf50b
    ('456-1456', '(', '帶分數開始'),    # \xf504
    ('456-3456', ')', '帶分數結束'),    # \xf507
    ('345', '√(', '根號'),         # \xf32a
    ('126', '√[', '根指數'),       # \xf32c (index of radical; 345 then types "](")
    ('12456', ')', '結束'),             # \xf32b termination
    ('45', '^', '上標'),                # \xf321
    ('56', '_', '下標'),                # \xf320
    ('5', '', '基線'),                  # pass2 @5
    ('146', '_(', '下方'),              # \xf322 underscript (lim 146 x→0 12456)
    ('4-6-12356', '[', '矩陣左括號'),   # \xf332
    ('4-6-23456', ']', '矩陣右括號'),   # \xf333
    ('46-56', '', '斜體'),
    ('46-46', '', '斜體結束'),
    ('456-56', '', '粗體'),
    ('456-456', '', '粗體結束'),
]
# 大寫符：Nemeth 的點 6 接字母（capsletter 6）。點 7 的八點大寫照舊可用。
LETTERS = {
    'a': '1', 'b': '12', 'c': '14', 'd': '145', 'e': '15', 'f': '124', 'g': '1245', 'h': '125', 'i': '24', 'j': '245',
    'k': '13', 'l': '123', 'm': '134', 'n': '1345', 'o': '135', 'p': '1234', 'q': '12345', 'r': '1235', 's': '234', 't': '2345',
    'u': '136', 'v': '1236', 'w': '2456', 'x': '1346', 'y': '13456', 'z': '1356',
}
for letter, cells in LETTERS.items():
    INDICATORS.append(('6-' + cells, letter.upper(), '大寫 ' + letter.upper()))
LETTER_CELLS = set(LETTERS.values())
DIGIT_CELLS = {'2', '23', '25', '256', '26', '235', '2356', '236', '35', '356'}


def parse_louis(path, want_opcodes):
    """yield (char, [cells as strings]) for character-definition lines.
    Virtual dot a is nothing; a blank cell (0) at either end is the word
    boundary Liblouis writes around relations and is dropped; a blank in
    the middle is a real space, which the engine cannot hold, so the entry
    is skipped; virtual dots b-f skip the entry too."""
    for raw in open(path, encoding='utf-8', errors='replace'):
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        parts = line.split()
        if len(parts) < 3 or parts[0] not in want_opcodes:
            continue
        chars, dots = parts[1], parts[2]
        m = re.fullmatch(r'\\x([0-9A-Fa-f]{4})', chars)
        if m:
            ch = chr(int(m.group(1), 16))
        elif chars == '\\\\':
            ch = '\\'
        elif chars == '\\s':
            ch = ' '
        elif len(chars) == 1:
            ch = chars
        else:
            continue
        raw_cells = [''.join(x for x in c if x != 'a') for c in dots.split('-')]
        raw_cells = [c for c in raw_cells if c != '']
        while raw_cells and raw_cells[0] == '0':
            raw_cells.pop(0)
        while raw_cells and raw_cells[-1] == '0':
            raw_cells.pop()
        cells = []
        ok = True
        for c in raw_cells:
            if not dots_mask(c):
                ok = False
                break
            cells.append(c)
        if ok and cells:
            yield ch, cells


seqs = {}        # 'dots-dots' -> (char, source)
collisions = {}  # 'dots-dots' -> [(char, source)] of the entries that lost
unnamed = {}     # char -> (cells, source)
def add(ch, cells, source):
    key = '-'.join(cells)
    if ch in EXCLUDE or key in EXCLUDE_CELLS:
        return
    if all(c in DIGIT_CELLS for c in cells) and not ch.isdigit():   # • 35-35, ⋯ 25-25-25: those are digits
        return
    if len(cells) == 1 and cells[0] in LETTER_CELLS:  # ⅆ 145, ⅇ 15, ʼ 12: those are letters
        return
    if ch not in NAMES:
        unnamed.setdefault(ch, (key, source))
        return
    if key in seqs:
        if seqs[key][0] != ch:
            collisions.setdefault(key, []).append((ch, source))
        return
    seqs[key] = (ch, source)


# Priority: the digits (a period 256 in nemeth.ctb must not shadow the digit 4),
# then nemeth.ctb's own rules for ASCII (midnum excluded: it says * between
# numbers is shown as 4-16, which is the times sign's cell; prepunc excluded:
# the opening quotes are the digits 8 and 0), then nemethdefs.cti, then the
# single cells of en-chardefs.cti.
for ch, cells in parse_louis(os.path.join(liblouis, 'loweredDigits6Dots.uti'), {'digit'}):
    add(ch, cells, 'loweredDigits6Dots.uti')
for ch, cells in parse_louis(os.path.join(liblouis, 'nemeth.ctb'), {'always', 'endnum', 'decpoint', 'hyphen', 'postpunc'}):
    add(ch, cells, 'nemeth.ctb')
for ch, cells in parse_louis(os.path.join(liblouis, 'nemethdefs.cti'), {'math', 'sign', 'lowercase', 'uppercase'}):
    add(ch, cells, 'nemethdefs.cti')
for ch, cells in parse_louis(os.path.join(liblouis, 'en-chardefs.cti'), {'punctuation', 'sign', 'math'}):
    add(ch, cells, 'en-chardefs.cti')

# nemethdefs.cti lists "not perpendicular" under the same code point as
# perpendicular (a typo in the source); a 34-prefixed negation that maps to the
# very character it negates is dropped.
for key in list(seqs):
    if key.startswith('34-') and key[3:] in seqs and seqs[key[3:]][0] == seqs[key][0]:
        del seqs[key]

entries = []
for key, (ch, source) in seqs.items():
    v = NAMES[ch]
    text, spoken = (v if isinstance(v, tuple) else (ch, v))
    entries.append((key, text, spoken, source, ch))
for key, text, spoken in INDICATORS:
    for e in entries:
        if e[0] == key and e[4]:
            collisions.setdefault(key, []).append((e[4], e[3]))
    entries = [e for e in entries if e[0] != key]
    entries.append((key, text, spoken, 'Nemeth indicator', ''))


def sort_key(e):
    return [int(c) for c in e[0].split('-')]


entries.sort(key=sort_key)
in_force = {e[0]: e for e in entries}


def c_wstr(s):
    return 'L"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def uname(ch):
    try:
        return unicodedata.name(ch)
    except ValueError:
        return 'U+%04X' % ord(ch)


with open(os.path.join(src_dir, 'nemeth.inc'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by tools/gen_tables.py from %s - do not edit by hand.\n' % liblouis)
    f.write('// { cells "dots-dots", text to type, spoken name }  Nemeth mathematics\n')
    f.write('//\n// Cells that the source tables give to more than one character. The first\n')
    f.write('// definition in priority order (digits, nemeth.ctb, nemethdefs.cti,\n')
    f.write('// en-chardefs.cti, then the indicators above all) is the one in force;\n')
    f.write('// the others cannot be typed by these cells:\n')
    for key in sorted(collisions, key=lambda k: [int(c) for c in k.split('-')]):
        w = in_force[key]
        winner = ('%s %s' % (w[4], uname(w[4]))) if w[4] else ('indicator %s' % w[2])
        losers = ', '.join('%s %s (%s)' % (c, uname(c), s) for c, s in collisions[key])
        f.write('//   %-12s = %s   not: %s\n' % (key, winner, losers))
    for key, text, spoken, source, ch in entries:
        f.write('{ "%s", %s, %s },  // %s %s\n' % (key, c_wstr(text), c_wstr(spoken), source, ('U+%04X' % ord(ch)) if ch else ''))
print('nemeth.inc:', len(entries), 'entries;', len(collisions), 'cell sequences with more than one character;', len(unnamed), 'unnamed characters skipped')
for ch in sorted(unnamed):
    key, source = unnamed[ch]
    print('  unnamed U+%04X %s %s (%s)' % (ord(ch), uname(ch), key, source))
